services:
  - type: web
    name: product-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myshop.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DJANGO_SETTINGS_MODULE
        value: myshop.settings
    autoDeploy: true

databases:
  - name: product-db
