services:
  - type: web
    name: product-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myshop.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: productapi-db
          property: connectionString

databases:
  - name: productapi-db
    region: oregon
    plan: free
    type: postgresql