services:
  - type: web
    name: product-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myshop.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

databases:
  - name: product-db
